#!/usr/bin/env ruby
require "rubygems"
require "benchmark"
require "stringio"

$LOAD_PATH << "#{File.dirname(__FILE__)}/../lib"
$LOAD_PATH << "#{File.dirname(__FILE__)}/../vendor"
require "trollop"
require "cover"

options = Trollop::options do
  opt :config, "Configuration file", :type => :string, :required => true
  opt :tiles, "Tile indices", :type => :strings
  opt :metatiles, "Metatile indices", :type => :strings
  opt :size, "Metatile size", :type => :integer, :default => 8
end

if options[:tiles] == nil && options[:metatiles] == nil
  Trollop::die "must specify either tiles or metatiles"
end

require File.expand_path(options[:config])
  
if !Cover.config.respond_to?(:maker)
  puts "Config file must assign to Cover.config an object which responds to #maker"
  exit
end

if Cover.config.respond_to?(:setup)
  Cover.config.setup
end

# assemble tile indices

def process_index_list(list)
  
  result = []
  
  list.each do |index|
  
    # if an index is a file, read tile indexes from that file, skipping
    # lines that start with "#".
  
    if File.exist?(index)
      File.open(index, "r").each_line do |line|
        next if line =~ /^#/ || line =~ /^\s*$/
        result << Cover::TileIndex::Slippy.new(line)
      end
    else
      result << Cover::TileIndex::Slippy.new(index)
    end
  
  end
  
  result
  
end

tiles = process_index_list(options[:tiles] || [])
metatiles = process_index_list(options[:metatiles] || [])

# do benchmarking

puts "%-20s  %7s  %7s" % ["Tile", "Time", "Size"]
puts "=" * 38

total_time = 0.0
total_size = 0

tiles.each do |tile|
  
  io = StringIO.new("")
  
  start = Time.now
  Cover.config.maker.write_tile(tile, io)
  
  time = Time.now - start
  size = io.string.bytesize
  
  total_time += time
  total_size += size
  
  puts "%-20s  % 7.3f  % 7.3f" % [tile, time, size.to_f / (1024 * 1024)]
  
end

puts "-" * 38
puts "%-20s  % 7.3f  % 7.3f" % ["Total", total_time, (total_size.to_f / (1024 * 1024))]
puts "%-20s  % 7.3f  % 7.3f" % ["Mean", total_time / tiles.size, (total_size.to_f / (1024 * 1024)) / tiles.size]

if Cover.config.respond_to?(:teardown)
  Cover.config.teardown
end
