#!/usr/bin/env ruby
require "rubygems"
require "rack"

$LOAD_PATH << "#{File.dirname(__FILE__)}/../lib"
$LOAD_PATH << "#{File.dirname(__FILE__)}/../vendor"
require "trollop"
require "cover"

options = Trollop::options do
  opt :config, "Configuration file", :type => :string, :required => true
  opt :center, "Initial map center (<lat>,<lon>,<zoom>)", :type => :string
  opt :port, "Port", :type => :integer, :default => 3857
  opt :host, "Host", :type => :string, :default => "0.0.0.0"
end

config = Cover::Util.load_config(options[:config])

config.setup if Cover.config.respond_to?(:setup)

Rack::Server.start(
  :app => Cover::Viewer.new(:center => options[:center], :maker => config.maker),
  :Host => options[:host],
  :Port => options[:port]
)

config.teardown if Cover.config.respond_to?(:teardown)
