#!/usr/bin/env ruby
require "rubygems"

$LOAD_PATH << "#{File.dirname(__FILE__)}/../lib"
$LOAD_PATH << "#{File.dirname(__FILE__)}/../vendor"
require "trollop"
require "cover"

options = Trollop::options do
  opt :size, "Metatile size", :type => :integer, :default => 8
  opt :config, "Configuration file", :type => :string, :required => true
  opt :index, "Tile index (z/x/y)", :type => :string, :required => true
end

if ARGV.size != 1
  Trollop::die "must specify an output path for the metatile"
end

options[:output] = ARGV[0]

# check that the metatile size is a power of 2

if (options[:size] & (options[:size] - 1)) != 0
  Trollop::die "metatile size must be a power of 2"
end

# get tile index

options[:index] = begin
  Cover::Index.from_string(options[:index])
rescue ArgumentError
  Trollop::die "invalid tile index"
end

# config file

require File.expand_path(options[:config])
  
if !Cover.config.respond_to?(:maker)
  puts "Config file must assign to Cover.config an object which responds to #maker"
  exit
end

# set up, write the metatile, and teardown

Cover.config.setup

File.open(options[:output], "wb+") do |f|
  Cover.config.maker.write_metatile(options[:index], options[:size], f)
end

Cover.config.teardown
