#!/usr/bin/env ruby
require "rubygems"

$LOAD_PATH << "#{File.dirname(__FILE__)}/../lib"
$LOAD_PATH << "#{File.dirname(__FILE__)}/../vendor"
require "trollop"
require "cover"

options = Trollop::options do
  opt :tile, "Tile index", :type => :string, :required => true
end

tile_index = Cover::TileIndex.new(options[:tile])
bounds = tile_index.bounds

parameters = {
  "left" => bounds.left,
  "top" => bounds.top,
  "right" => bounds.right,
  "bottom" => bounds.bottom,
  "width" => bounds.width,
  "height" => bounds.height
}

parameters.each do |k,v|
  puts "#{k} = #{v}"
end
