#!/usr/bin/env ruby
require "rubygems"
require "rack"

$LOAD_PATH << "./#{File.dirname(__FILE__)}/../lib"
$LOAD_PATH << "./#{File.dirname(__FILE__)}/../vendor"
require "trollop"
require "cover"
require "./#{File.dirname(__FILE__)}/../debug/debug"

options = Trollop::options do
  opt :config, "Configuration file (.rb)", :type => :string
end

options[:tile] = ARGV[0]

if options[:tile] == nil
  Trollop::die "must specify a tile index"
end

if options[:config] == nil
  Trollop::die "must specify either a config file with --config"
end

index = nil

begin
  index = Cover::Index.from_string(options[:tile])
rescue ArgumentError
  Trollop::die "tile index must be of the form z/x/y"
end

require File.expand_path(options[:config])

if Cover.config == nil
  puts "Configuration file must set Cover.config"
  exit
end

Cover.config.setup

puts Cover.config.maker.render_tile(index)

Cover.config.teardown
