#!/usr/bin/env ruby
require "rubygems"

$LOAD_PATH << "#{File.dirname(__FILE__)}/../lib"
$LOAD_PATH << "#{File.dirname(__FILE__)}/../vendor"
require "cover"

def usage
  puts "Usage: script/tile <config>.rb z/x/y"
  exit
end

if ARGV.size != 2
  usage
end

options = {
  config: ARGV[0],
  tile: ARGV[1]
}

index = begin
  Cover::Index.from_string(options[:tile])
rescue ArgumentError
  usage
end

require File.expand_path(options[:config])

if !Cover.config.respond_to?(:maker)
  puts "Config file must assign to Cover.config an object which responds to #maker"
  exit
end

Cover.config.setup
puts Cover.config.maker.render_tile(index)
Cover.config.teardown
