#!/usr/bin/env ruby
require "rubygems"
require "rack"

$LOAD_PATH << "#{File.dirname(__FILE__)}/../lib"
$LOAD_PATH << "#{File.dirname(__FILE__)}/../vendor"
require "trollop"
require "cover"

options = Trollop::options do
  opt :center, "Initial map center as lat,lon,zoom, for example: 37.7392,-122.3011,9", :type => :string
  opt :port, "Port", :type => :integer, :default => 3857
  opt :host, "Host", :type => :string, :default => "0.0.0.0"
end

if ARGV.size == 0
  Trollop::die "must specify a tileset file"
end

options[:tileset] = ARGV[0]

if !File.exist?(options[:tileset])
  puts "Tileset file doesn't exist: #{options[:tileset]}"
  exit
end

database = SQLite3::Database.new(options[:tileset])
tileset = Cover::Tileset.new(database)

Rack::Server.start(
  :app => Cover::Viewer.new(options.merge(tileset: tileset)),
  :Host => options[:host],
  :Port => options[:port]
)
